name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        
        run: npm test
    

  deploy:
        needs: [test]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Vercel CLI
              run: npm install --global vercel

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.A }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.A }}

            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --token=${{ secrets.A }}